FROM python:3.12

#LABEL org.opencontainers.image.source="https://github.com/josecostamc/oml-class"

WORKDIR /app

COPY frontend/index.html /app/index.html

CMD ["python", "-m", "http.server", "5002"]