services:
  mlflow-tracking-server:
    container_name: mlflow-tracking-server
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --port 5000 --host 0.0.0.0 --backend-store-uri ./mlruns --artifacts-destination ./mlruns
    volumes:
      - ./mlruns:/mlruns
    ports:
      - 5000:5000

  lending-prediction-service:
    build:
      context: .
      dockerfile: Dockerfile.Service
      tags:
        - lending-prediction-service:latest
    container_name: lending-prediction-service
    ports:
      - 5001:5001

  lending-prediction-ui:
    build:
      context: .
      dockerfile: Dockerfile.UI
      tags:
        - lending-prediction-ui:latest
    container_name: lending-prediction-ui
    ports:
      - 5002:5002
