name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install docker
        uses: docker/setup-buildx-action@v3

      - name: Tracking server + Service + UI
        run: docker compose up -d --build

      - name: install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: venv
          environment-file: conda.yaml     

      - name: Tests
        run: conda run --no-capture-output --name venv pytest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: docker push service
        run: docker push ghcr.io/josecostamc/lending-prediction-service

      - name: docker push ui
        run: docker push ghcr.io/josecostamc/lending-prediction-ui